Feat/erc3525
Carbonable/carbonable-contracts pull request #7
Opened 2022-11-14 16:21 UTC by tekkac

closes #2 
Draft PR for review.
Additional tests to be added.

2022-11-14 18:25 UTC, Bal7hazar requested changes

2022-11-14 18:25 UTC, bal7hazar commented on src/carbonable/erc3525/library.cairo
> +        ERC721.initializer(name, symbol);
Did you consider to have the ERC721 initializer in the contract instead of the library?

2022-11-14 18:25 UTC, bal7hazar commented on src/carbonable/erc3525/IERC3525.cairo
> +    func valueDecimals3525() -> (decimals: felt) {
Remove 3525 suffix if not technically blocking (as discussed together)

2022-11-15 14:54 UTC, tekkac commented on src/carbonable/erc3525/IERC3525.cairo
> +    func valueDecimals3525() -> (decimals: felt) {
done

2022-11-15 14:54 UTC, tekkac commented on src/carbonable/erc3525/library.cairo
> +        ERC721.initializer(name, symbol);
indeed

2022-11-21 16:48 UTC, Bal7hazar approved these changes
LGTM, huge work on tests :+1: 

Minor comments:
- Why did you have renamed ERC3525.cairo into ERC3525Example.cairo instead of using a presets folder ? (OZ style)
- Why remove Ownership assertions, is it to stay as close as possible of the EIP (no assumption about what must or not be owner only)?

2022-11-22 00:19 UTC, cloudvenger approved these changes

2022-11-22 09:08 UTC, merged